spring:
  profiles:
    active:
    - dev
 
---
server:
  port: 8001
spring:
  profiles: dev
  application: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    passwor: 1230
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-mills: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        
  type-aliases-package: com.atguigu.springcloud.entities   
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       

eureka:
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8003
    prefer-ip-address: true     
      
info: 
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$  



---
server:
  port: 8001
spring:
  profiles: test
  application: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02
    username: root
    passwor: 1230
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-mills: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        
  type-aliases-package: com.atguigu.springcloud.entities   
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       

eureka:
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8003
    prefer-ip-address: true     
      
info: 
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$  
  
