spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
spring:
  profiles: dev 
  application:
    name: microservicecloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/
      
---

spring:
  profiles: test
  application:
    name: microservicecloud-config
eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com:7001/eureka/